services:
  db:
    image: postgres:17-alpine
    container_name: project-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: project-mailhog
    restart: always
    ports:
      - '1025:1025' # SMTP port
      - '8025:8025' # Web-UI port

volumes:
  postgres_data:
